apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    autopilot.gke.io/resource-adjustment: '{"input":{"containers":[{"name":"kubemq-sources"}]},"output":{"containers":[{"limits":{"ephemeral-storage":"1Gi"},"requests":{"cpu":"500m","ephemeral-storage":"1Gi","memory":"2Gi"},"name":"kubemq-sources"}]},"modified":true}'
    autopilot.gke.io/warden-version: 3.0.42
    deployment.kubernetes.io/revision: "1"
    kubemq.io/deployment-cluster-id: 43087ca9979551cd6181cd65fad4805148690a1b8c63778fdfee77be99f5b518
    kubemq.io/deployment-created-at: "2025-01-09T16:03:33Z"
    kubemq.io/deployment-id: QMEjJLxvBd1DxEK7qxQfJ4
    kubemq.io/deployment-subtype: sources
    kubemq.io/deployment-type: connector
  creationTimestamp: "2025-01-09T16:03:33Z"
  generation: 1
  labels:
    app: kubemq-sources
  managedFields:
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          .: {}
          f:kubemq.io/deployment-cluster-id: {}
          f:kubemq.io/deployment-created-at: {}
          f:kubemq.io/deployment-id: {}
          f:kubemq.io/deployment-subtype: {}
          f:kubemq.io/deployment-type: {}
        f:labels:
          .: {}
          f:app: {}
        f:ownerReferences:
          .: {}
          k:{"uid":"9c1955a5-0291-48f6-a9a4-40a1e00c82e7"}: {}
      f:spec:
        f:progressDeadlineSeconds: {}
        f:replicas: {}
        f:revisionHistoryLimit: {}
        f:selector: {}
        f:strategy:
          f:rollingUpdate:
            .: {}
            f:maxSurge: {}
            f:maxUnavailable: {}
          f:type: {}
        f:template:
          f:metadata:
            f:annotations:
              .: {}
              f:prometheus.io/path: {}
              f:prometheus.io/port: {}
              f:prometheus.io/scrape: {}
            f:labels:
              .: {}
              f:app: {}
          f:spec:
            f:containers:
              k:{"name":"kubemq-sources"}:
                .: {}
                f:env:
                  .: {}
                  k:{"name":"CHECKSUM"}:
                    .: {}
                    f:name: {}
                    f:value: {}
                f:image: {}
                f:imagePullPolicy: {}
                f:name: {}
                f:ports:
                  .: {}
                  k:{"containerPort":8080,"protocol":"TCP"}:
                    .: {}
                    f:containerPort: {}
                    f:protocol: {}
                f:resources: {}
                f:terminationMessagePath: {}
                f:terminationMessagePolicy: {}
                f:volumeMounts:
                  .: {}
                  k:{"mountPath":"/kubemq-connector/config.yaml"}:
                    .: {}
                    f:mountPath: {}
                    f:name: {}
                    f:subPath: {}
            f:dnsPolicy: {}
            f:restartPolicy: {}
            f:schedulerName: {}
            f:securityContext: {}
            f:terminationGracePeriodSeconds: {}
            f:volumes:
              .: {}
              k:{"name":"config-file"}:
                .: {}
                f:configMap:
                  .: {}
                  f:defaultMode: {}
                  f:items: {}
                  f:name: {}
                f:name: {}
    manager: kubemq-operator
    operation: Update
    time: "2025-01-09T16:03:33Z"
  - apiVersion: apps/v1
    fieldsType: FieldsV1
    fieldsV1:
      f:metadata:
        f:annotations:
          f:deployment.kubernetes.io/revision: {}
      f:status:
        f:availableReplicas: {}
        f:conditions:
          .: {}
          k:{"type":"Available"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
          k:{"type":"Progressing"}:
            .: {}
            f:lastTransitionTime: {}
            f:lastUpdateTime: {}
            f:message: {}
            f:reason: {}
            f:status: {}
            f:type: {}
        f:observedGeneration: {}
        f:readyReplicas: {}
        f:replicas: {}
        f:updatedReplicas: {}
    manager: kube-controller-manager
    operation: Update
    subresource: status
    time: "2025-01-09T16:03:36Z"
  name: kubemq-sources
  namespace: kubemq
  ownerReferences:
  - apiVersion: core.k8s.kubemq.io/v1beta1
    blockOwnerDeletion: true
    controller: true
    kind: KubemqConnector
    name: kubemq-sources
    uid: 9c1955a5-0291-48f6-a9a4-40a1e00c82e7
  resourceVersion: "39357"
  uid: e32c45ea-c55f-48fc-b126-4e5988313fbc
spec:
  progressDeadlineSeconds: 600
  replicas: 1
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: kubemq-sources
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      annotations:
        prometheus.io/path: /metrics
        prometheus.io/port: "8080"
        prometheus.io/scrape: "true"
      creationTimestamp: null
      labels:
        app: kubemq-sources
    spec:
      containers:
      - env:
        - name: CHECKSUM
          value: cdd0c82e22036b4164f9e7d9b4cf3c06cb9d7aedecee8825943ec53845767268
        image: docker.io/kubemq/kubemq-sources:latest
        imagePullPolicy: Always
        name: kubemq-sources
        ports:
        - containerPort: 8080
          protocol: TCP
        resources:
          limits:
            ephemeral-storage: 1Gi
          requests:
            cpu: 500m
            ephemeral-storage: 1Gi
            memory: 2Gi
        securityContext:
          capabilities:
            drop:
            - NET_RAW
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
        volumeMounts:
        - mountPath: /kubemq-connector/config.yaml
          name: config-file
          subPath: config.yaml
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext:
        seccompProfile:
          type: RuntimeDefault
      terminationGracePeriodSeconds: 30
      tolerations:
      - effect: NoSchedule
        key: kubernetes.io/arch
        operator: Equal
        value: amd64
      volumes:
      - configMap:
          defaultMode: 420
          items:
          - key: config.yaml
            path: config.yaml
          name: kubemq-sources-config
        name: config-file
status:
  availableReplicas: 1
  conditions:
  - lastTransitionTime: "2025-01-09T16:03:36Z"
    lastUpdateTime: "2025-01-09T16:03:36Z"
    message: Deployment has minimum availability.
    reason: MinimumReplicasAvailable
    status: "True"
    type: Available
  - lastTransitionTime: "2025-01-09T16:03:33Z"
    lastUpdateTime: "2025-01-09T16:03:36Z"
    message: ReplicaSet "kubemq-sources-665dfc999" has successfully progressed.
    reason: NewReplicaSetAvailable
    status: "True"
    type: Progressing
  observedGeneration: 1
  readyReplicas: 1
  replicas: 1
  updatedReplicas: 1
